appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: kvlnLVpziDeYVKBu6reHuFtnAO3bPniHs0sXoTuEaMnRkzrTwH4SpnRmjNV15tyqby0xYQVA4WLaoVui3mGTb3DRZZvidt0VzjpU2i9gkQ97U7JK5CiPlIgjR61Nsgw8C0u66EVqxiK7yzxbVO9hTokMAEM4uT5SZetHfVw6uZG9aofLKcq+frfT7h4+pIW07H8EUTfAG+8ZjtBnxtrV9ZMWsB73mI9zJvHfrK1zXgMCdtCbNFwvxDn75hs5P8MSfOO1xk7zZBbfksHiZNK7ZVm+lhvY3tKRBRrOD6+WwTIyGlWigkrVGtppK2ot2TmWhVptydN78TW/4gkIYoLXVevph71DB99ZBK3M6daheMLrBxY2dEnTZ/0N/LHYWJuajeVYV2wJJgmcqRJFoiBxMWEr3EjqxRAYrzOeuzrCqqaHWwlJD7YOFghF9z5OnOC9HO2ZpUaKRwQ07ml1CjbsWL5fh2kqE7Q/RwEF9VxyGcjwJvtpdBCv/FwbRDv8aIsjgN8gAnrBI8z6IykSW6VKeWyVoCT+SChOV+rIg6VGy9pEVW33uJQ9HLrvirIYFeiYjl5ZjpEXjIbtkdx8NSdHdWZDe5Cp/RwcoLF2sBKPGhkqBiiHUQcPdrk5kj6q3XmIAAgE9PUMwZedROsDqkI/5GhHiumPpdO3XVfnnZITcQU=}
provider:
  osx: travis
conda_forge_output_validation: true
